@startuml Classes and Interfaces
' skinparam linetype ortho

class Investor implements Account {
- name: String
+ setName()
}

interface "InvestmentAccount" {
  primaryKey: number
  activeAccount: boolean
  singleMutualFund: boolean
  statusTransactionCount: unknown
  financialInstitution: string
  creationTimestamp: Date
  modificationTimestamp: Date
  currency: string
  globalUID: unknown
  accountName: string
  notes: string
  typeName: string
  closed: boolean
  isActive(): boolean
}

class "InvestmentAccountImpl" implements InvestmentAccount {

}

@enduml