@startuml Quicken ERM
' skinparam linetype ortho

entity "ZACCOUNT" {
  * **Z_PK: INTEGER <<PK>>**
  * Z_ENT: INTEGER
  * Z_OPT: INTEGER
  * ZACTIVE: INTEGER
  * ZCANDIDATENOCASHTRANSACTIONS: INTEGER
  * ZCANDIDATESINGLEMUTUALFUND: INTEGER
  * ZCLOSED: INTEGER
  * ZCONFIRMATIONNEEDED: INTEGER
  * ZCOSTBASISALGORITHMDEBT: INTEGER
  * ZCOSTBASISALGORITHMMUTUALFUND: INTEGER
  * ZCOSTBASISALGORITHMOPTION: INTEGER
  * ZCOSTBASISALGORITHMOTHER: INTEGER
  * ZCOSTBASISALGORITHMSTOCK: INTEGER
  * ZDELETIONCOUNT: INTEGER
  * ZIMPORTQID: INTEGER
  * ZLASTCHECKNUM: INTEGER
  * ZLIQUIDITY: INTEGER
  * ZLOANCOMPOUNDINGPERIOD: INTEGER
  * ZLOANHASBEENSETUP: INTEGER
  * ZLOANHASOFFEREDTOCONVERTLIABILITY: INTEGER
  * ZLOANPAYMENTFREQUENCY: INTEGER
  * ZLOANPAYMENTPERIOD: INTEGER
  * ZLOANRATETYPE: INTEGER
  * ZLOANTERMTYPE: INTEGER
  * ZLOANUSEMATURITYDATE: INTEGER
  * ZMOSTRECENTDOWNLOADSESSIONNUMBER: INTEGER
  * ZNOCASHTRANSACTIONS: INTEGER
  * ZOFXPAYMENTSENABLED: INTEGER
  * ZOFXTRANSFERDESTENABLED: INTEGER
  * ZOFXTRANSFERSOURCEENABLED: INTEGER
  * ZONLINEBANKINGACCOUNTINFOSESSIONNEEDED: INTEGER
  * ZONLINEBANKINGACCOUNTISENABLED: INTEGER
  * ZONLINEBANKINGACCOUNTISINBIDCHANGE: INTEGER
  * ZONLINEBANKINGAWAITINGINITIALDOWNLOAD: INTEGER
  * ZONLINEBANKINGCHANGEPINFIRSTCOMPLETED: INTEGER
  * ZQUICKENID: INTEGER
  * ZSCHEDULELOOKAHEADVALUE: INTEGER
  * ZSIMPLEINVESTING: INTEGER
  * ZSINGLEMUTUALFUND: INTEGER
  * ZSTATUSNUMATTEMPTS: INTEGER
  * ZSTATUSTRANSACTIONCOUNT: INTEGER
  * ZSYNCRESETREQUIRED: INTEGER
  * ZSYNCWITHCLOUD: INTEGER
  * ZTAXABLE: INTEGER
  * ZUSEDINAUTOUPDATES: INTEGER
  * ZUSEDINREPORTS: INTEGER
  * ZBILLPAYPAYMENTACCOUNT: INTEGER
  * ZBILLPAYPROVIDERINSTITUTION: INTEGER
  * ZCLOUDFILOGIN: INTEGER
  * ZERROR: INTEGER
  * ZFINANCIALINSTITUTION: INTEGER
  * ZLOANINTERESTCATEGORY: INTEGER
  * ZLOANSMARTTRANSACTION: INTEGER
  * ZCLOSEDDATE: TIMESTAMP
  * ZCREATIONTIMESTAMP: TIMESTAMP
  * ZLOANFIRSTPAYMENTDATE: TIMESTAMP
  * ZLOANNEXTPAYMENTDATE: TIMESTAMP
  * ZMODIFICATIONTIMESTAMP: TIMESTAMP
  * ZONLINEBANKINGLASTCONNECTEDTIMESTAMP: TIMESTAMP
  * ZONLINEBANKINGLEDGERBALANCEDATE: TIMESTAMP
  * ZREVIEWEDTIMESTAMP: TIMESTAMP
  * ZCREDITLIMIT: DECIMAL
  * ZINTERESTRATE: DECIMAL
  * ZLOANOPENINGBALANCE: DECIMAL
  * ZLOANTERM: DECIMAL
  * ZONLINEBANKINGLEDGERBALANCEAMOUNT: DECIMAL
  * ZBANKROUTINGNUMBER: VARCHAR
  * ZBILLPAYROUTINGNUMBER: VARCHAR
  * ZCHECKPRINTINGPROPERTIESJSON: VARCHAR
  * ZCURRENCY: VARCHAR
  * ZDATASOURCE: VARCHAR
  * ZFILTERSJSON: VARCHAR
  * ZGUID: VARCHAR
  * ZIMPORTSOURCEFILEID: VARCHAR
  * ZIMPORTSOURCEID: VARCHAR
  * ZNAME: VARCHAR
  * ZNOTES: VARCHAR
  * ZNOTIFICATIONSJSON: VARCHAR
  * ZOFXBILLPAYSERVICESTATUS: VARCHAR
  * ZOFXLASTBANKMAILTOKEN: VARCHAR
  * ZOFXLASTPAYMENTTOKEN: VARCHAR
  * ZOFXLASTTRANSFERTOKEN: VARCHAR
  * ZONLINEBANKINGACCOUNTNUMBER: VARCHAR
  * ZONLINEBANKINGAGGREGATORACCOUNTID: VARCHAR
  * ZONLINEBANKINGCONNECTIONTYPE: VARCHAR
  * ZONLINEBANKINGCUSTOMERID: VARCHAR
  * ZONLINEBANKINGDTEND: VARCHAR
  * ZONLINEBANKINGLASTTOKEN: VARCHAR
  * ZONLINEBANKINGLASTUUID: VARCHAR
  * ZONLINEBANKINGOFXACCOUNTTYPE: VARCHAR
  * ZONLINEBANKINGPREVIOUSBID: VARCHAR
  * ZONLINEBANKINGSERVERID: VARCHAR
  * ZONLINEBILLPAYACCOUNTNUMBER: VARCHAR
  * ZONLINEBILLPAYCONNECTIONTYPE: VARCHAR
  * ZONLINEBILLPAYCUSTOMERID: VARCHAR
  * ZONLINEBILLPAYOFXACCOUNTTYPE: VARCHAR
  * ZRECONCILEINFOJSON: VARCHAR
  * ZREGIONCODE: VARCHAR
  * ZSCHEDULELOOKAHEADUNITTYPE: VARCHAR
  * ZSYNCID: VARCHAR
  * ZTYPENAME: VARCHAR
  * ZUSERDESCRIPTION: VARCHAR
  * ZCHECKPRINTINGPROPERTIES: BLOB
  * ZFILTERS: BLOB
  * ZNOTIFICATIONS: BLOB
  * ZRECONCILEINFO: BLOB
  * ZANOMALOUSSYNCSTATUS: BLOB
  * ZONLINEBANKINGACCOUNTNUMBERMASKED: VARCHAR
  * ZONLINEBANKINGAGGREGATIONPENDINGENABLEMENTINFO: BLOB
  * ZONLINEBANKINGAGGREGATIONENABLEMENTCOUNT: INTEGER
  * ZONLINEBANKINGAGGREGATIONDISABLEMENTCOUNT: INTEGER
  * ZONLINEBANKINGACCOUNTDESCRIPTION: VARCHAR
  * ZAUTORECONCILE: INTEGER
  * ZQ17SYNCID: VARCHAR
}

entity "ZSECURITY" {
  * **Z_PK: INTEGER <<PK>>**
  * Z_ENT: INTEGER
  * Z_OPT: INTEGER
  * ZCOSTBASISALGORITHM: INTEGER
  * ZDEBTRATINGTYPE: INTEGER
  * ZDEBTTYPE: INTEGER
  * ZDELETIONCOUNT: INTEGER
  * ZHIDEINLISTS: INTEGER
  * ZINTERESTFREQUENCYTYPE: INTEGER
  * ZQUICKENID: INTEGER
  * ZSHOULDDOWNLOADQUOTES: INTEGER
  * ZTAXFREE: INTEGER
  * ZTYPE: INTEGER
  * ZWATCHLIST: INTEGER
  * ZCOUPONMATURITYDATE: TIMESTAMP
  * ZCREATIONTIMESTAMP: TIMESTAMP
  * ZDEBTCALLDATE: TIMESTAMP
  * ZDEBTMATURITYDATE: TIMESTAMP
  * ZEXPIREDATE: TIMESTAMP
  * ZLATESTQUOTEDATE: TIMESTAMP
  * ZMODIFICATIONTIMESTAMP: TIMESTAMP
  * ZMOSTRECENTQUOTEDOWNLOADTIMESTAMP: TIMESTAMP
  * ZASSETCLASSPERCENTAGEDOMESTICBOND: DECIMAL
  * ZASSETCLASSPERCENTAGEINTLBOND: DECIMAL
  * ZASSETCLASSPERCENTAGEINTLSTOCK: DECIMAL
  * ZASSETCLASSPERCENTAGELARGESTOCK: DECIMAL
  * ZASSETCLASSPERCENTAGEMONEYMRKT: DECIMAL
  * ZASSETCLASSPERCENTAGEOTHER: DECIMAL
  * ZASSETCLASSPERCENTAGESMALLSTOCK: DECIMAL
  * ZBACKLOADFEERATE: DECIMAL
  * ZCOUPONRATE: DECIMAL
  * ZDEBTMATURITYRATE: DECIMAL
  * ZFACEVALUEUNITPRICE: DECIMAL
  * ZLATESTCLOSINGPRICE: DECIMAL
  * ZLATESTPRICECHANGE: DECIMAL
  * ZLATESTPRICECHANGEPERCENT: DECIMAL
  * ZSHARESPERCONTRACT: DECIMAL
  * ZSTRIKEPRICE: DECIMAL
  * ZASSETCLASS: VARCHAR
  * ZDATASOURCE: VARCHAR
  * ZGOALSTRING: VARCHAR
  * ZGUID: VARCHAR
  * ZISSUETYPE: VARCHAR
  * ZNAME: VARCHAR
  * ZOPTIONTYPE: VARCHAR
  * ZSYNCID: VARCHAR
  * ZTICKER: VARCHAR
  * ZASSETMIXTUREDATAISUSERDEFINED: INTEGER
  * ZASSETCLASSPERCENTAGECASH: DECIMAL
}


entity "ZLOT" {
  * **Z_PK: INTEGER <<PK>>**
  * Z_ENT: INTEGER 
  * Z_OPT: INTEGER 
  * ZDELETIONCOUNT: INTEGER 
  * ZQUICKENID: INTEGER 
  * **ZPOSITION: INTEGER <<FK>>** 
  * ZACQUISITIONDATE: TIMESTAMP 
  * ZCREATIONTIMESTAMP: TIMESTAMP 
  * ZINITIALTRANSACTIONDATE: TIMESTAMP 
  * ZLATESTTRANSACTIONDATE: TIMESTAMP 
  * ZMODIFICATIONTIMESTAMP: TIMESTAMP 
  * ZINITIALCOSTBASIS: DECIMAL 
  * ZINITIALUNITS: DECIMAL 
  * ZLATESTCOSTBASIS: DECIMAL 
  * ZLATESTUNITS: DECIMAL 
  * ZDATASOURCE: VARCHAR 
  * ZGUID: VARCHAR 
  * ZSYNCID: VARCHAR
}

entity "ZLOTMOD" {
  * **Z_PK: INTEGER <<PK>>**
  * Z_ENT: INTEGER  
  * Z_OPT: INTEGER  
  * ZDELETIONCOUNT: INTEGER  
  * ZQUICKENID: INTEGER  
  * ZTERMTYPE: INTEGER  
  * ZTRANSACTIONQUICKENID: INTEGER  
  * **ZLOT: INTEGER <<FK>>**  
  * ZLOTASSIGNMENT: INTEGER  
  * **ZTRANSACTION: INTEGER <<FK>>**  
  * ZCREATIONTIMESTAMP: TIMESTAMP  
  * ZMODIFICATIONTIMESTAMP: TIMESTAMP  
  * ZTRANSACTIONDATE: TIMESTAMP (UNDEFINED) 
  * ZAFTERCOSTBASIS: DECIMAL  
  * ZAFTERPOSITIONCOSTBASIS: DECIMAL  
  * ZAFTERPOSITIONUNITSDECIMAL  
  * ZAFTERUNITS: DECIMAL  
  * ZBEFORECOSTBASIS: DECIMAL  
  * ZBEFOREUNITS: DECIMAL  
  * ZDATASOURCE: VARCHAR  
  * ZGUID: VARCHAR
  * ZSYNCID: VARCHAR
}

entity "ZPOSITION" {
  * **Z_PK: INTEGER <<PK>>**
  * Z_ENT: INTEGER  
  * Z_OPT: INTEGER  
  * ZCOSTBASISALGORITHM: INTEGER  
  * ZDELETIONCOUNT: INTEGER  
  * ZQUICKENID: INTEGER  
  * ZTYPE: INTEGER (UNKNOWN PURPOSE)
  * **ZACCOUNT: INTEGER <<FK>>**  
  * **ZSECURITY: INTEGER <<FK>>**  
  * ZCREATIONTIMESTAMP: TIMESTAMP  
  * ZMODIFICATIONTIMESTAMP: TIMESTAMP  
  * ZDATASOURCE: VARCHAR  
  * ZGUID: VARCHAR  
  * ZSYNCID: VARCHAR  
  * ZUNIQUEID: VARCHAR  
  * ZUNIQUEIDTYPE: VARCHAR  
}

entity "ZTRANSACTION" {
  * **Z_PK: INTEGER <<PK>>**
  * Z_ENT: INTEGER
  * Z_OPT: INTEGER
  * ZDELETIONCOUNT: INTEGER
  * ZEXCLUDEFROMREPORTS: INTEGER
  * ZIGNORETHISCASHTRANSACTION: INTEGER
  * ZIMPORTQID: INTEGER
  * ZLOCKED: INTEGER
  * ZMATCHED: INTEGER
  * ZONLINEID: INTEGER
  * ZORDERID: INTEGER
  * ZQUICKENID: INTEGER
  * ZRECONCILESTATUS: INTEGER
  * ZTYPE: INTEGER
  * ZUSERSTATUSOVERRIDE: INTEGER
  * **ZACCOUNT: INTEGER <<ZK>>**
  * ZDOWNLOADSESSION: INTEGER
  * ZERROR: INTEGER
  * **ZFITRANSACTION: INTEGER <<FK>>**
  * ZPLACEHOLDERACCOUNT: INTEGER
  * ZRECONCILEDTRANSACTION: INTEGER
  * ZRENAMINGRULEUSED: INTEGER
  * ZSENDACCOUNT: INTEGER
  * ZTARGETACCOUNT: INTEGER
  * ZFLAG: INTEGER
  * ZMACHINEGENERATEDCATEGORYSOURCE: INTEGER
  * ZMACHINEGENERATEDPAYEESOURCE: INTEGER
  * ZMACHINEGENERATEDTAGSOURCE: INTEGER
  * ZMISCFLAGS: INTEGER
  * ZSENDREQUESTSTATE: INTEGER
  * ZSOURCESMARTCASHFLOWTRANSACTIONQUICKENID: INTEGER
  * ZACTION: INTEGER
  * ZCHECKPAYCHECK: INTEGER
  * ZQUICKPAYPAYMENT: INTEGER
  * ZUSERPAYEE: INTEGER
  * ZAUTOPOST: INTEGER
  * ZTOBESENT: INTEGER
  * ZLOANACCOUNT: INTEGER
  * ZCOSTBASISALGORITHM: INTEGER
  * ZTAXEXEMPT: INTEGER
  * **ZPOSITION: INTEGER <<FK>>**
  * ZCREATIONTIMESTAMP: TIMESTAMP
  * ZENTEREDDATE: TIMESTAMP
  * ZMODIFICATIONTIMESTAMP: TIMESTAMP
  * ZPLACEHOLDERTARGETDATE: TIMESTAMP
  * ZPOSTEDDATE: TIMESTAMP
  * ZBUDGETFLEXIBILITY: FLOAT
  * ZSENTTRANSACTIONSTATUSDATE: TIMESTAMP
  * ZSOURCESMARTCASHFLOWTRANSACTIONORIGINALMODELDATE: TIMESTAMP
  * ZACQUISITIONDATE: TIMESTAMP
  * **ZAMOUNT: DECIMAL**
  * ZPLACEHOLDERTARGETBALANCE: DECIMAL
  * ZCOMMISSION: DECIMAL
  * ZCOSTBASIS: DECIMAL
  * ZDENOMINATOR: DECIMAL
  * ZNUMERATOR: DECIMAL
  * ZPLACEHOLDERCOSTBASIS: DECIMAL
  * ZPLACEHOLDERCOSTBASISUNITS: DECIMAL
  * ZPLACEHOLDERTARGETUNITS: DECIMAL
  * ZPLACEHOLDERUNITSONTARGETDATE: DECIMAL
  * ZUNITS: DECIMAL
  * ZDATASOURCE: VARCHAR
  * ZFINOTE: VARCHAR
  * ZGUID: VARCHAR
  * ZIMPORTSOURCEFILEID: VARCHAR
  * ZIMPORTSOURCEID: VARCHAR
  * ZMATCHSOURCE: VARCHAR
  * ZNOTE: VARCHAR
  * ZONLINEBANKINGSERVERID: VARCHAR
  * ZPREMATCHPROPERTIESJSON: VARCHAR
  * ZREFERENCE: VARCHAR
  * ZSYNCID: VARCHAR
  * ZCHECKNUMBER: VARCHAR
  * ZCHECKPROPERTIESJSON: VARCHAR
  * ZCLIENTASSIGNEDTRANSACTIONUID: VARCHAR
  * ZOFXPAYEELISTID: VARCHAR
  * ZRECURRENCEJSON: VARCHAR
  * ZLOCATION: BLOB
  * ZPREMATCHPROPERTIES: BLOB
  * ZCHECKPROPERTIES: BLOB
  * ZRECURRENCEEND: BLOB
}

package "ZFI" {
  entity "ZFITRANSACTION" {
    * **Z_PK: INTEGER <<PK>>**
    * Z_ENT: INTEGER
    * Z_OPT: INTEGER
    * ZCCCATEGORYID: INTEGER
    * ZDELETIONCOUNT: INTEGER
    * ZQUICKENID: INTEGER
    * ZTYPE: INTEGER
    * **ZACCOUNT: INTEGER <<FK>>**
    * ZCREATIONTIMESTAMP: TIMESTAMP
    * ZMODIFICATIONTIMESTAMP: TIMESTAMP
    * ZPOSTEDDATE: TIMESTAMP
    * ZACCRUEDINTEREST: DECIMAL
    * ZAMOUNT: DECIMAL
    * ZCOMMISSION: DECIMAL
    * ZDENOMINATOR: DECIMAL
    * ZFEES: DECIMAL
    * ZLOAD: DECIMAL
    * ZNUMERATOR: DECIMAL
    * ZPENALTY: DECIMAL
    * ZSTATEWITHHOLDING: DECIMAL
    * ZTAXES: DECIMAL
    * ZUNITS: DECIMAL
    * ZWITHHOLDING: DECIMAL
    * ZCCCATEGORYNAME: VARCHAR
    * ZCCPAYEENAME: VARCHAR
    * ZDATASOURCE: VARCHAR
    * ZFITRANSACTIONID: VARCHAR
    * ZGUID: VARCHAR
    * ZIMPORTSOURCEFILEID: VARCHAR
    * ZINCOMETYPE: VARCHAR
    * ZPOSTYPE: VARCHAR
    * ZSERVERTRANSID: VARCHAR
    * ZSTATEMENTPAYEENAME: VARCHAR
    * ZSYNCID: VARCHAR
    * ZUNIQUEID: VARCHAR
    * ZUNIQUEIDTYPE: VARCHAR
  }

  entity "ZFISTATEMENT" {
    * **Z_PK: INTEGER <<PK>>**
    * Z_ENT: INTEGER
    * Z_OPT: INTEGER
    * ZDELETIONCOUNT: INTEGER
    * ZQUICKENID: INTEGER
    * **ZACCOUNT: INTEGER <<FK>>**
    * ZCREATIONTIMESTAMP: TIMESTAMP
    * ZDATEASOF: TIMESTAMP
    * ZMODIFICATIONTIMESTAMP: TIMESTAMP
    * ZAVAILCASH: DECIMAL
    * ZMARGINBALANCE: DECIMAL
    * ZSHORTBALANCE: DECIMAL
    * ZDATASOURCE: VARCHAR
    * ZGUID: VARCHAR
    * ZSYNCID: VARCHAR
  }

  entity "ZFIPOSITION" {
    * **Z_PK: INTEGER <<PK>>**
    * Z_ENT: INTEGER
    * Z_OPT: INTEGER
    * ZDELETIONCOUNT: INTEGER
    * ZQUICKENID: INTEGER
    * ZSECURITYTYPE: INTEGER
    * **ZFISTATEMENT: INTEGER <<FK>>**
    * ZCOUPONMATURITYDATE: TIMESTAMP
    * ZCREATIONTIMESTAMP: TIMESTAMP
    * ZDEBTMATURITYDATE: TIMESTAMP
    * ZEXPIREDATE: TIMESTAMP
    * ZMODIFICATIONTIMESTAMP: TIMESTAMP
    * ZASSETCLASSPERCENTAGEDOMESTICBOND: DECIMAL
    * ZASSETCLASSPERCENTAGEINTLBOND: DECIMAL
    * ZASSETCLASSPERCENTAGEINTLSTOCK: DECIMAL
    * ZASSETCLASSPERCENTAGELARGESTOCK: DECIMAL
    * ZASSETCLASSPERCENTAGEMONEYMRKT: DECIMAL
    * ZASSETCLASSPERCENTAGEOTHER: DECIMAL
    * ZASSETCLASSPERCENTAGESMALLSTOCK: DECIMAL
    * ZCOUPONRATE: DECIMAL
    * ZMARKETVALUE: DECIMAL
    * ZSECURITYUNITPRICE: DECIMAL
    * ZSHARESPERCONTRACT: DECIMAL
    * ZSTRIKEPRICE: DECIMAL
    * ZUNITPRICE: DECIMAL
    * ZUNITS: DECIMAL
    * ZASSETCLASS: VARCHAR
    * ZDATASOURCE: VARCHAR
    * ZGUID: VARCHAR
    * ZISSUETYPE: VARCHAR
    * ZMEMO: VARCHAR
    * ZOPTIONTYPE: VARCHAR
    * ZPOSTYPE: VARCHAR
    * ZSECURITYMEMO: VARCHAR
    * ZSECURITYNAME: VARCHAR
    * ZSECURITYTICKER: VARCHAR
    * ZSECURITYTYPEDESCRIPTION: VARCHAR
    * ZSYNCID: VARCHAR
    * ZUNIQUEID: VARCHAR
    * ZUNIQUEIDTYPE: VARCHAR
  }

  entity "ZFIBALANCE" {
    * **Z_PK: INTEGER <<PK>>**
    * Z_ENT: INTEGER
    * Z_OPT: INTEGER
    * ZDELETIONCOUNT: INTEGER
    * ZQUICKENID: INTEGER
    * **ZFISTATEMENT: INTEGER <<FK>>**
    * ZCREATIONTIMESTAMP: TIMESTAMP
    * ZMODIFICATIONTIMESTAMP: TIMESTAMP
    * ZBALANCEVALUE: DECIMAL
    * ZBALANCEDESCRIPTION: VARCHAR
    * ZBALANCETYPE: VARCHAR
    * ZDATASOURCE: VARCHAR
    * ZGUID: VARCHAR
    * ZNAME: VARCHAR
    * ZSYNCID: VARCHAR
  }
}

ZFIBALANCE -- ZFISTATEMENT
ZFIPOSITION ||--|| ZFISTATEMENT
ZPOSITION }o--|| ZSECURITY
ZTRANSACTION }o--|| ZPOSITION
ZTRANSACTION }o--|| ZACCOUNT
ZTRANSACTION ||--|| ZLOTMOD
ZTRANSACTION -- ZFITRANSACTION
ZFITRANSACTION -- ZACCOUNT
ZACCOUNT ||--o{ ZPOSITION
ZACCOUNT -- ZFISTATEMENT
ZPOSITION ||--|{ ZLOT
ZLOT ||--o{ ZLOTMOD

@enduml